sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Use Python 3.7 on xenial with sudo since it's not available on trusty yet
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  global:
  - PACKAGENAME="mvision_edr_activity_feed"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev --skip-lock # TODO: improve pipenv running

# command to run tests
script:
  - pytest --cov-report term --cov-report html:cov_html --cov-config=.coveragerc --cov=$PACKAGENAME
  
# run coverage
after_success:
  - coveralls
