sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Use Python 3.7 on xenial with sudo since it's not available on trusty yet
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --skip-lock # TODO: improve pipenv running
  #- pipenv shell

# command to run tests
script:
  #- python setup.py ci
  - python -m unittest -v tests.test_activityfeed
