sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Use Python 3.7 on xenial with sudo since it's not available on trusty yet
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  global:
    # List package dependencies for conda (Package, dependency and environment management for any language—Python: https://docs.conda.io/en/latest/)
    # https://stackoverflow.com/questions/20994716/what-is-the-difference-between-pip-and-conda
    - CONDA_DEPS="pytest numpy"
    # package name for test invocation
    - PACKAGENAME="activityfeed"

before_install:
  # Here we download miniconda and install the dependencies
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $MINICONDA
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install $CONDA_DEPS

# command to install dependencies
install:
  - pip install .[test]
  # Install through setup.py should be redundant because of the preceding pip
  # install. Just doing this to try to catch any high-level errors.
  - python setup.py install

# command to run tests
script:
  #- python setup.py ci
  - pytest $PACKAGENAME
